spring:
  application:
      name: admin-service
      config:
          uri: http://discovery:8000

server:
  port: 8050

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
management:
  security:
    enabled: false
endpoints:
  health:
    sensitive: false

