version: '2'
services:
  discovery:
    image: gt/eureka-service
    ports:
      - "8761:8761"
  eureka-client:
    image: gt/eureka-client
    ports:
      - "8762:8762"
  gateway-service:
    image: gt/gateway-service
    ports:
      - "8888:8888"
  kpmservice:
    image: mskpm
    ports:
      - "8090:8090"
  
